version: '3.9'

services:
  app:
    build: .
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
        - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fastapi_db
    restart: always
    networks:
        - fastapi_network

  db:
    image: postgres:16.4
    container_name: fastapi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
        - fastapi_network

volumes:
    postgres_data:

networks:
    fastapi_network:
        driver: bridge