from .department_schema import DepartmentSchema
from .employee_schema import EmployeeSchema
from .client_schema import ClientSchema, ClientVisitHistorySchema
from .attendance_schema import EmployeeAttendanceSchema
from .working_graphic_schema import WorkingGraphicSchema